### ISSUE TITLE
Support for Zeus?

### ISSUE THREAD

**Issue by satel-kalletuulos** [thin-edge/meta-tedge#6]
Thank you for this great meta layer. :) Currently, the meta layer supports only Kirkstone. Do you know, what are dependencies, if it would be possible to port the meta-tedge for Zeus?

**Comment by Bravo555** [comment]
Hello, thanks :) The layer currently only supports Kirkstone, because our dependency for building Rust projects on Yocto, [meta-rust layer](https://github.com/meta-rust/meta-rust) was in Kirkstone added to Yocto core. For other versions, I think we can support them if meta-rust itself does support them, and meta-rust appears to support Zeus, so we'll be looking into that.

**Comment by Bravo555** [comment]
Unfortunately, meta-rust for Zeus has only Rust version 1.51, and thin-edge.io requires at least version 1.58.1 to be built. By `layer.conf` file of meta-rust, it looks like Rust 1.58.1 will be available for: dunfell, gatesgarth, hardknott, and honister versions. I'm going to check if thin-edge.io can be built on them, but you're probably out of luck on Zeus, because it looks like meta-rust also no longer supports it.

As for our layer, we can consider supporting what's currently supported by meta-rust, so Dunfell (3.1) would be the oldest possible version that we can support.

**Comment by satel-kalletuulos** [comment]
Thank you for this information. I discuss with BSP provider what are their plans, when they would upgrade to at least Dunfell.

**Comment by satel-kalletuulos** [comment]
BSP provider has experimental support for Honister i.e. 3.4. So, I tested, whether meta-tedge can be used with that, and short answer is yes.

Steps were:
1. I changed the layer.conf of meta-tedge to support also honister.
2. I removed everything related to rust and cargo from under "meta" layer.
3. Added meta-rust layer from github.
4. Deleted 1.54.0 related classes recipes from meta-rust layer.

After these, "bitbake tedge-image" went without errors, and "tedge" client seemed to work under qemu. At least, it was able to create its own certificate.

**Comment by Ruadhri17** [comment]
Great! @Bravo555 is working on it. The Honister branch should appear next week.

**Comment by Bravo555** [comment]
Just published a branch for honister, which properly specifies meta-rust as a dependency and overrides preferred Rust toolchain version to 1.58.1, so there should be no need to delete any files to make bitbake pick up correct Rust version.

**Comment by Ruadhri17** [comment]
Now onister operates correctly (does not produce warning about rust version) under the same branch with the kirkstone release. Closing the issue!
